# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fast_scandir": "00_pictures.ipynb",
         "mypath": "00_pictures.ipynb",
         "my_Dirs": "00_pictures.ipynb",
         "stat_data": "00_pictures.ipynb",
         "entry_data": "00_pictures.ipynb",
         "df1": "00_pictures.ipynb",
         "df2": "00_pictures.ipynb",
         "df": "00_pictures.ipynb",
         "df_duplicates": "00_pictures.ipynb"}

modules = ["pictures.py"]

doc_url = "https://aloiswirth.github.io/sort_fotos/"

git_url = "https://github.com/aloiswirth/sort_fotos/tree/main/"

def custom_doc_links(name): return None
