# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["pictures.py"]

doc_url = "https://aloiswirth.github.io/sort_fotos/"

git_url = "https://github.com/aloiswirth/sort_fotos/tree/main/"

def custom_doc_links(name): return None
