# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_pictures.ipynb (unless otherwise specified).

__all__ = ['fast_scandir', 'mypath', 'my_Dirs', 'stat_data', 'entry_data', 'df1', 'df2', 'df', 'df_duplicates']

# Cell

import os
import pandas as pd
from os.path import isfile, join


# Cell

mypath = r"/media/mycloud/My Pictures"

def fast_scandir(dirname):
    subfolders= [f.path for f in os.scandir(dirname) if f.is_dir()]
    for dirname in list(subfolders):
        subfolders.extend(fast_scandir(dirname))
    return subfolders
my_Dirs = fast_scandir(mypath)

# Cell
stat_data = []
entry_data = []

for dirname in my_Dirs:
    with os.scandir(dirname) as dir_content:
        for entry in dir_content:
            if isfile(join(dirname, entry)):
                info = entry.stat()
                stat_data.append(info)
                entry_data.append([dirname, entry.name, entry.path])

# Cell
df1 = pd.DataFrame(entry_data)

# Cell
df1.rename(columns={0: "directory", 1: "file_name", 2: "absolute_file_name"}, inplace=True)
# df1.head()

# Cell
df2 = pd.DataFrame(stat_data)
df2.rename(columns={ 0 : "st_mode", 1: "st_ino", 2 : "st_dev", 3 : "st_nlink", 4 : "st_uid", 5: "st_gid",}, inplace=True)
df2.rename(columns={ 6 : "st_size", 7 : "st_atime", 8 : "st_mtime", 9 : "st_ctime"}, inplace=True)

# Cell
df = pd.concat([df1, df2], axis=1)
df.head()

# Cell
df.sort_values("file_name", inplace=True)
df.head()

# Cell
df.duplicated(subset=['file_name'])

# Cell
df_duplicates = df[df['file_name'].duplicated(keep=False)]
len(df_duplicates)

# df[df.duplicated(['ID'], keep=False)]
# data.sort_values(by=['Order ID'], inplace=True)
# df = data[data['Order ID'].duplicated(keep=False)]


# Cell
df_duplicates[80:113]