# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "01_card.ipynb"}

modules = ["card.py"]

doc_url = "https://aloiswirth.github.io/nbdev_tutorial/"

git_url = "https://github.com/aloiswirth/nbdev_tutorial/tree/master/"

def custom_doc_links(name): return None
